In [1]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np
import pandas as pd

In [3]:
books = pd.read_csv('books.csv')
users = pd.read_csv('users.csv')
rating = pd.read_csv('ratings.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'books.csv'

In [4]:
books = pd.read_csv('books.csv')
users = pd.read_csv('users.csv')
rating = pd.read_csv('ratings.csv')

C:\Users\Dell\AppData\Local\Temp\ipykernel_40500\790862924.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('books.csv')

In [5]:
low_memory=False.

SyntaxError: invalid syntax (3945096020.py, line 1)

In [6]:
set low_memory=False.

SyntaxError: invalid syntax (383113372.py, line 1)

In [7]:
books = pd.read_csv('books.csv' , low_memory=False)
users = pd.read_csv('users.csv' , low_memory=False)
ratings = pd.read_csv('ratings.csv' , low_memory=False)

In [8]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

Popularity Based System

In [10]:
Book_Rating = ratings.merge(books,on='ISBN')

In [11]:
Book_Rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [12]:
rating_no_df = Book_Rating.groupby('Book-Title').count()['Book-Rating'].reset_index()
rating_no_df.rename(columns={'Book-Rating' : 'ratings_no'},inplace = True)
rating_no_df

                                               Book-Title  ratings_no
0        A Light in the Storm: The Civil War Diary of ...           4
1                                   Always Have Popsicles           1
2                    Apple Magic (The Collector's series)           1
3        Ask Lily (Young Women of Faith: Lily Series, ...           1
4        Beyond IBM: Leadership Marketing and Finance ...           1
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.           2
241067                     Ã?Â?rger mit Produkt X. Roman.           4
241068                                Ã?Â?sterlich leben.           1
241069                              Ã?Â?stlich der Berge.           3
241070                                  Ã?Â?thique en toc           2

[241071 rows x 2 columns]

In [13]:
rating_avg_df = Book_Rating.groupby('Book-Title').mean()['Book-Rating'].reset_index()
rating_avg_df.rename(columns={'Book-Rating' : 'ratings_avg'},inplace = True)
rating_avg_df

TypeError: agg function failed [how->mean,dtype->object]

In [14]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [15]:
rating_avg_df = Book_Rating.groupby('Book-Title').sum()['Book-Rating'].reset_index()
rating_avg_df.rename(columns={'Book-Rating' : 'ratings_avg'},inplace = True)
rating_avg_df

                                               Book-Title  ratings_avg
0        A Light in the Storm: The Civil War Diary of ...            9
1                                   Always Have Popsicles            0
2                    Apple Magic (The Collector's series)            0
3        Ask Lily (Young Women of Faith: Lily Series, ...            8
4        Beyond IBM: Leadership Marketing and Finance ...            0
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            0
241067                     Ã?Â?rger mit Produkt X. Roman.           21
241068                                Ã?Â?sterlich leben.            7
241069                              Ã?Â?stlich der Berge.            8
241070                                  Ã?Â?thique en toc            8

[241071 rows x 2 columns]

In [16]:
rating_avg_df = Book_Rating.groupby('Book-Title').mean()['Book-Rating'].reset_index()
rating_avg_df.rename(columns={'Book-Rating' : 'ratings_avg'},inplace = True)
rating_avg_df

TypeError: agg function failed [how->mean,dtype->object]

In [17]:
pd.to_numeric(df[1], errors='coerce').mean()

NameError: name 'df' is not defined

In [18]:
rating_avg_df = Book_Rating.groupby('Book-Title').sum()/count()['Book-Rating'].reset_index()
rating_avg_df.rename(columns={'Book-Rating' : 'ratings_avg'},inplace = True)
rating_avg_df

NameError: name 'count' is not defined

In [19]:
rating_avg_df = Book_Rating.groupby('Book-Title')['Book-Rating'].sum() / Book_Rating.groupby('Book-Title')['Book-Rating'].count()
rating_avg_df = rating_avg_df.reset_index()
rating_avg_df.rename(columns={'Book-Rating': 'ratings_avg'}, inplace=True)
rating_avg_df

                                               Book-Title  ratings_avg
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [20]:
popular_df = rating_no_df.merge(rating_avg_df)

In [21]:
popular_df = rating_no_df.merge(rating_avg_df,on = 'Book-Title')
popular_df

,Book-Title,ratings_no,ratings_avg
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [22]:
popular_df[popular_df['ratings_no'>200].sort_values('ratings_avg',ascending= False)

SyntaxError: incomplete input (4286722431.py, line 1)

In [23]:
popular_df[popular_df['ratings_no'>=200].sort_values('ratings_avg',ascending= False)

SyntaxError: incomplete input (1738607748.py, line 1)

In [24]:
popular_df[popular_df['ratings_no']>=200].sort_values('ratings_avg',ascending= False)

,Book-Title,ratings_no,ratings_avg
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
60582,Ender's Game (Ender Wiggins Saga (Paperback)),249,5.409639
...,...,...,...
27600,Breathing Lessons,239,2.117155
94382,Isle of Dogs,288,2.000000
162153,Slow Waltz in Cedar Bend,248,1.895161
163913,Songs in Ordinary Time (Oprah's Book Club (Pap...,232,1.857759
234951,Wild Animus,2502,1.019584

In [30]:
popular_df = popular_df[popular_df['ratings_no']>=200].sort_values('ratings_avg',ascending= False).head(25)

In [28]:
popular_df.merge(books,on='Book-Title')

,Book-Title,ratings_no,ratings_avg,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000,0590567330,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...
1,Always Have Popsicles,1,0.000000,0964147726,Rebecca Harvin,1994,Rebecca L. Harvin,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...
2,Apple Magic (The Collector's series),1,0.000000,0942320093,Martina Boudreau,1984,Amer Cooking Guild,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000,0310232546,Nancy N. Rue,2001,Zonderkidz,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000,0962295701,Lou Mobley,1989,"Teleonet, Incorporated",http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...
...,...,...,...,...,...,...,...,...,...,...
270291,Ã?Â?lpiraten.,2,0.000000,3499232499,Janwillem van de Wetering,2002,Rowohlt Tb.,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...
270292,Ã?Â?rger mit Produkt X. Roman.,4,5.250000,325721538X,Joan Aiken,1987,Diogenes Verlag,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...
270293,Ã?Â?sterlich leben.,1,7.000000,3451274973,Anselm GrÃ?Â¼n,2001,"Herder, Freiburg",http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...
270294,Ã?Â?stlich der Berge.,3,2.666667,3442725739,David Guterson,2000,btb,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...
270295,Ã?Â?thique en toc,2,4.000000,2842192508,Didier Daeninckx,1998,Baleine,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...

In [32]:
popular_df = popular_df[popular_df['ratings_no']>=200].sort_values('ratings_avg',ascending= False).head(25)

In [37]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','ratings_no','ratings_avg']]

In [38]:
popular_df

,Book-Title,Book-Author,Image-URL-M,ratings_no,ratings_avg
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Ender's Game (Ender Wiggins Saga (Paperback)),Orson Scott Card,http://images.amazon.com/images/P/0312853238.0...,249,5.409639
17,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
20,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
21,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
30,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
32,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
43,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
51,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
57,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
59,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
66,"The Return of the King (The Lord of the Rings,...",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339738.0...,211,4.497630
76,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
77,The Great Gatsby,F. Scott Fitzgerald,http://images.amazon.com/images/P/185326041X.0...,205,4.458537
79,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
88,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
89,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
94,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
100,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
101,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
104,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
105,Brave New World,Aldous Huxley,http://images.amazon.com/images/P/0060809833.0...,226,4.331858